Sharmila-Textile-WebApp/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
 
namespace Sharmila_Textile_WebApp.Models {
    [Table("SUPPLIER")]
    public class Supplier {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("SUPPLIER_ID")]
        public long SupplierId { get; set; }

        [Column("SUPPLIER_NAME", TypeName = "varchar(50)")]
        public string SupplierName { get; set; }

        [Column("ADDRESS", TypeName = "varchar(max)")]
        public string Address { get; set; }

        [Column("LANDLINE", TypeName = "nchar(10)")]
        public string Landline { get; set; }

        [Column("MOBILE", TypeName = "nchar(10)")]
        public string Mobile { get; set; }

        [Column("OPENING_BALANCE", TypeName = "decimal(18, 2)")]
        public decimal OpeningBalance { get; set; }

        [Column("CURRENT_BALANCE", TypeName = "decimal(18, 2)")]
        public decimal CurrentBalance { get; set; }

        [Column("CREATE_DATE", TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }

        [Column("CREATED_BY")]
        public long CreatedBy { get; set; }

        [Column("CURRENT_STATUS", TypeName = "int")]
        public int CurrentStatus { get; set; }

        [ForeignKey("CreatedBy")]
        public User User { get; set; }
    }
}

Sharmila-Textile-WebApp/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sharmila_Textile_WebApp.Data;
using Sharmila_Textile_WebApp.Models;
using Sharmila_Textile_WebApp.ViewModel;

namespace Sharmila_Textile_WebApp.Controllers {
    public class SupplierController : Controller {
        private readonly AppDBContext _context;
        private readonly IMapper _mapper;
        [Obsolete]
        private readonly IHostingEnvironment _hostingEnvironment;

        [Obsolete]
        public SupplierController(AppDBContext context, IMapper mapper, IHostingEnvironment hostingEnvironment) {
            _context = context;
            _mapper = mapper;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult SupplierView() {
            if (HttpContext.Session.GetString("loggedIn") == null || HttpContext.Session.GetString("loggedIn") == "false") {
                return RedirectToAction("Index", "Login");
            }
            var data = from a in _context.Suppliers
                       join b in _context.Users on a.CreatedBy equals b.UserId where a.CurrentStatus == 1
                       select new SupplierViewModel {
                           SupplierId = a.SupplierId, SupplierName = a.SupplierName, Address = a.Address, Landline = a.Landline, 
                           Mobile = a.Mobile, OpeningBalance = a.OpeningBalance, CurrentBalance = a.CurrentBalance, CreatedDate = a.CreatedDate, 
                           CreatedBy = a.CreatedBy, CurrentStatus = a.CurrentStatus,
                           UserName = b.UserName
                       };
            return View(data);
        }

        [Obsolete]
        public IActionResult SupplierDetailView(string breadCumValue, int supplierId) {
            if (HttpContext.Session.GetString("loggedIn") == null || HttpContext.Session.GetString("loggedIn") == "false") {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.breadcumValue = breadCumValue;
            ViewBag.IsUpdate = supplierId > 0 ? "true" : "false";

            if (supplierId > 0) {
                Supplier supplier = _context.Suppliers.FirstOrDefault(x => x.SupplierId == supplierId);
                List<SupplierAttachment> supplierAttachments =
                    _context.SupplierAttachments.Where(x => x.SupplierId == supplierId).ToList();

                SupplierViewModel model = _mapper.Map<SupplierViewModel>(supplier);

                List<SupplierAttachmentViewModel> supplierAttachmentViewModelList = new List<SupplierAttachmentViewModel>();
                foreach (var item in supplierAttachments) {
                    SupplierAttachmentViewModel supplierAttachmentViewModel = new SupplierAttachmentViewModel {
                        SupplierId = item.SupplierId,
                        AttachmentName = item.AttachmentName,
                        AttachmentRandomName = item.AttachmentPath
                    };

                    string path = _hostingEnvironment.WebRootPath + @"\files\" + item.AttachmentPath;
                    byte[] data = System.IO.File.ReadAllBytes(path);
                    supplierAttachmentViewModel.AttachmentFile = item.MimeType + "," + Convert.ToBase64String(data);
                    supplierAttachmentViewModelList.Add(supplierAttachmentViewModel);
                }

                model.SupplierAttachmentList = supplierAttachmentViewModelList;
                return View(model);
            }
            return View();
        }

        public IActionResult SupplierInfoView(string breadCumValue, int supId) {
            if (HttpContext.Session.GetString("loggedIn") == null || HttpContext.Session.GetString("loggedIn") == "false") {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.breadcumValue = breadCumValue;

            var data = (from a in _context.Suppliers
                join b in _context.Users on a.CreatedBy equals b.UserId 
                join c in _context.Staffs on b.StaffId equals c.StaffId
                where a.CurrentStatus == 1 && a.SupplierId == supId
                        select new SupplierViewModel {
                    SupplierId = a.SupplierId, SupplierName = a.SupplierName, Address = a.Address, Landline = a.Landline,
                      Mobile = a.Mobile, OpeningBalance = a.OpeningBalance,
                    CurrentBalance = a.CurrentBalance, CreatedDate = a.CreatedDate, CreatedBy = a.CreatedBy, CurrentStatus = a.CurrentStatus,
                    UserName = c.StaffName
                }).SingleOrDefault();
            return View(data);
        }

    }
}

Sharmila-Textile-WebApp/Views/Supplier/SupplierInfoView.cshtml
@model Sharmila_Textile_WebApp.ViewModel.SupplierViewModel

@{
    ViewData["Title"] = "Supplier Info View";
}


<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="SupplierView">Supplier</a></li>
                    <li class="breadcrumb-item active" aria-current="page">@ViewBag.breadcumValue</li>
                </ol>
            </nav>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        @* <span class="notification">5</span> *@
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Mike John responded to your email</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="#">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Login" asp-action="Logout">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="content" id="printableArea">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <hr />
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card card-chart">
                    <div class="card-header card-header-success p-1 pt-2 pl-2">
                        <h5 class="card-title">Supplier Details</h5>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-lg-3 col-md-4 col-sm-6 form-inline">
                                        <h5 class="font-weight-bold mr-3">Supplier Name : </h5>
                                        <h5>@Model.SupplierName</h5>
                                    </div>
                                    <div class="col-lg-3 col-md-4 col-sm-6 form-inline">
                                        <h5 class="font-weight-bold mr-3">Address : </h5>
                                        <h5>@Model.Address</h5>
                                    </div>
                                    <div class="col-lg-3 col-md-4 col-sm-6 form-inline">
                                        <h5 class="font-weight-bold mr-3">Landline : </h5>
                                        <h5>@Model.Landline</h5>
                                    </div>
                                    <div class="col-lg-3 col-md-4 col-sm-6 form-inline">
                                        <h5 class="font-weight-bold mr-3">Mobile : </h5>
                                        <h5>@Model.Mobile</h5>
                                    </div>
                                    <div class="col-lg-3 col-md-4 col-sm-6 form-inline">
                                        <h5 class="font-weight-bold mr-3">Opening Balance : </h5>
                                        <h5>@Model.OpeningBalance</h5>
                                    </div>
                                    <div class="col-lg-3 col-md-4 col-sm-6 form-inline">
                                        <h5 class="font-weight-bold mr-3">Created Date : </h5>
                                        <h5>@Model.CreatedDate.ToString("yyyy-MM-dd")</h5>
                                    </div>
                                    <div class="col-lg-3 col-md-4 col-sm-6 form-inline">
                                        <h5 class="font-weight-bold mr-3">Created By : </h5>
                                        <h5>@Model.UserName</h5>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <hr />
                                    </div>
                                </div>
                                <div class="row justify-content-between">
                                    <div class="col-auto mt-auto">
                                        <button id="btnPrint" class="btn btn-primary d-print-none btn-success"><i class="material-icons mr-2">print</i>Print</button>
                                    </div>
                                    <div class="col-auto text-danger form-inline">
                                        <h3 class="font-weight-bold mr-3">Current Balance : </h3>
                                        <h3>@Model.CurrentBalance</h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card card-chart">
                    <div class="card-header card-header-info p-1 pt-2 pl-2">
                        <h5 class="card-title">Supplier Accounts</h5>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Account Type</th>
                                    <th class="text-right">Total Amount</th>
                                    <th class="text-center d-print-none">View</th>
                                </tr>
                            </thead>
                            <tbody id="tblAccount">
                            </tbody>
                        </table>
                        <div class="row justify-content-center">
                            <div class="col-auto">
                                <button class="btn btn-success pt-2 pb-2 d-print-none" id="btnLoadMoreAcc">
                                    <h5 style="height: 25px;" class="mb-0 pb-0 font-weight-bold">Load More</h5>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card card-chart">
                    <div class="card-header card-header-info p-1 pt-2 pl-2">
                        <h5 class="card-title">Supplier Payment</h5>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Payment Type</th>
                                    <th class="text-right">Total Amount</th>
                                    <th class="text-center d-print-none">View</th>
                                </tr>
                            </thead>
                            <tbody id="tblPayment">
                            </tbody>
                        </table>
                        <div class="row justify-content-center">
                            <div class="col-auto">
                                <button class="btn btn-success pt-2 pb-2 d-print-none" id="btnLoadMorePay">
                                    <h5 style="height: 25px;" class="mb-0 pb-0 font-weight-bold">Load More</h5>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('#btnPrint').click(function(){
        printDiv();
    });

    function printDiv() {
        var restorepage = $('body').html();
        var printcontent = $('#printableArea').clone();
        $('body').empty().html(printcontent);
        window.print();
        $('body').html(restorepage);
    }

    jQuery(document).bind("keyup keydown", function(e) {
        if (e.ctrlKey && e.keyCode === 80) {
            printDiv();
            return false;
        }
        return false;
    });

    var skipAcc = 0;
    var skipPay = 0;

    GetAccountList();
    GetPayment();

    $('#btnLoadMoreAcc').click(function() {
        $("#btnLoadMoreAcc").html(`<img src="/img/loading-v2.gif" style="max-height: 25px;" />`);
        GetAccountList();
    });

    $('#btnLoadMoreCol').click(function() {
        $("#btnLoadMoreCol").html(`<img src="/img/loading-v2.gif" style="max-height: 25px;" />`);
        GetPayment();
    });

    function GetAccountList() {

        $.ajax({
            url: localStorage.apiLink + "api/SupplierAccount/GetList/@Model.SupplierId/"+skipAcc,
            type: 'GET',
            contentType: 'application/json',
            success: function (data, textStatus, xhr) {
                var html = "";
                $("#btnLoadMoreAcc").html(`<h5 style="height: 25px;" class="mb-0 pb-0 font-weight-bold">Load More</h5>`);

                data.forEach(function (currentValue, index, arr) {
                    html += populateTable(currentValue.Date, currentValue.AccountType, currentValue.Amount, "/SupplierAccount/SupplierAccountListView");
                    skipAcc++;
                });
                $('#tblAccount').append(html);
            },
            error: function (xhr, textStatus, errorThrown) {
                $("#btnLoadMoreAcc").html(`<h5 style="height: 25px;" class="mb-0 pb-0 font-weight-bold">Load More</h5>`);
            }
        });
    }

    function GetPayment() {

        $.ajax({
            url: localStorage.apiLink + "api/SupplierPayment/GetList/@Model.SupplierId/"+skipPay,
            type: 'GET',
            contentType: 'application/json',
            success: function (data, textStatus, xhr) {
                var html = "";
                $("#btnLoadMorePay").html(`<h5 style="height: 25px;" class="mb-0 pb-0 font-weight-bold">Load More</h5>`);

                data.forEach(function (currentValue, index, arr) {
                    html += populateTable(currentValue.Date, currentValue.PaymentTypeName, currentValue.TotalAmount,  "/SupplierPayment/PaymentListView");
                    skipPay++;
                });
                $('#tblPayment').append(html);
            },
            error: function (xhr, textStatus, errorThrown) {
                $("#btnLoadMorePay").html(`<h5 style="height: 25px;" class="mb-0 pb-0 font-weight-bold">Load More</h5>`);
            }
        });
    }

    function populateTable(date, type, amount, actionLink) {
      return `<tr>
                <td>${moment(date).format('YYYY-MM-DD')}</td>
                <td>${type}</td>
                <td class="text-right">${amount}</td>
                    <td class="text-center d-print-none"><a class="btn btn-sm btn-primary text-white" target="_blank" href="`+actionLink+`?date=${moment(date).format('YYYY-MM-DD')}"><i class="fa fa-eye"></i><a></td>
            </tr>`;
    }

</script>

Sharmila-Textile-WebApp/Views/Supplier/SupplierView.cshtml
@model IQueryable<Sharmila_Textile_WebApp.ViewModel.SupplierViewModel>
@{
    ViewData["Title"] = "SupplierView";
}

<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Supplier</li>
                </ol>
            </nav>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="Search...">
                    <button type="button" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        @* <span class="notification">5</span> *@
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Mike John responded to your email</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="#">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Login" asp-action="Logout">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <hr />
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                <a class="btn btn-primary float-right" asp-controller="Supplier" asp-action="SupplierDetailView" asp-route-breadcumValue="Create New Supplier">
                    <i class="material-icons">add</i> Create Supplier
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card mt-0">
                    <div class="card-body">
                        <table id="dataTbl" class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Supplier Name</th> 
                                    <th>Address</th>
                                    <th>Landline</th> 
                                    <th>Mobile</th>
                                    <th>Opening Balance</th>
                                    <th>Current Balance</th>
                                    <th>Date Created</th>
                                    <th>Created by</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model) {
                                    <tr>
                                        <td class="text-center">@item.SupplierId</td>
                                        <td>@item.SupplierName</td>
                                        <td>@item.Address</td>
                                        <td>@item.Landline</td>
                                        <td>@item.Mobile</td>
                                        <td>@item.OpeningBalance.ToString("N2")</td>
                                        <td>@item.CurrentBalance.ToString("N2")</td>
                                        <td>@item.CreatedDate.ToString("yyyy-MM-dd")</td>
                                        <td>@item.UserName</td>
                                        <td class="td-actions">
                                            <a type="button" rel="tooltip" class="btn btn-success" asp-controller="Supplier" asp-action="SupplierDetailView" asp-route-breadcumValue="Edit @item.SupplierName" asp-route-supplierId="@item.SupplierId">
                                                <i class="material-icons">edit</i>
                                            </a>
                                            <button type="button" rel="tooltip" class="btn btn-danger" onclick="deleteConfirmation(@item.SupplierId)">
                                                <i class="material-icons">close</i>
                                            </button>
                                            <a type="button" rel="tooltip" class="btn btn-success" asp-action="SupplierInfoView" asp-route-breadcumValue="Viewing @item.SupplierName" asp-route-supId="@item.SupplierId">
                                                <i class="material-icons">visibility</i>
                                            </a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    $(function () {
        var myTable = $('#dataTbl').DataTable();
        $('#dataTbl_filter').addClass("float-right");
    });

    function deleteConfirmation(id) {

        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.value) {
                deleteItem(id);
            }
        });


    }

    function deleteItem(id) {
        $.ajax({
            url: localStorage.apiLink + "api/Supplier/Delete/" + id,
            type: 'get',
            contentType: 'application/json',
            success: function (data, textStatus, xhr) {
                if (data === true) {
                    document.location.reload(true);
                }
            },
            error: function (xhr, textStatus, errorThrown) {
                console.log('Error in Operation');
            }
        });
    }
</script>