Sharmila-Textile-WebApp/Models/BankDeposit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Sharmila_Textile_WebApp.Models {
    [Table("BANK_DEPOSIT")]
    public class BankDeposit {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("BANK_DEPOSIT_ID")]
        public long BankDepositId { get; set; }

        [Column("CASH", TypeName = "decimal(18, 2)")]
        public decimal Cash { get; set; }

        [Column("IN_HAND_CASH", TypeName = "decimal(18, 2)")]
        public decimal InHandCash { get; set; }

        [Column("TOTAL_AMOUNT", TypeName = "decimal(18, 2)")]
        public decimal TotalAmount { get; set; }

        [Column("DATE")]
        public DateTime Date { get; set; }

        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; }

        [Column("CREATED_BY")]
        public long CreatedBy { get; set; }

        [Column("STATUS")]
        public int Status { get; set; }

        [ForeignKey("CreatedBy")]
        public User User { get; set; }

        public List<BankDepositThirdPartyCheque> BankDepositThirdPartyCheques { get; set; }

    }
}

Sharmila-Textile-WebApp/Controllers/BankDepositController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks; 
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sharmila_Textile_WebApp.Data;
using Sharmila_Textile_WebApp.Models;
using Sharmila_Textile_WebApp.ViewModel;

namespace Sharmila_Textile_WebApp.Controllers {
  
    public class BankDepositController : Controller {
        private readonly AppDBContext _context;
        private readonly IMapper _mapper;

        public BankDepositController(AppDBContext context, IMapper mapper) {
             
            _context = context;
            _mapper = mapper;
        } 
         

        public IActionResult BankDepositListView(string date) {
            if (HttpContext.Session.GetString("loggedIn") == null || HttpContext.Session.GetString("loggedIn") == "false") {
                return RedirectToAction("Index", "Login");
            }
            List<BankDepositViewModel> data;
            if (date != null) {
                data = (from a in _context.BankDeposits
                        join b in _context.Users on a.CreatedBy equals b.UserId
                        join c in _context.Staffs on b.StaffId equals c.StaffId
                        where a.Status == 1 && a.Date == Convert.ToDateTime(date)
                        select new BankDepositViewModel {
                            BankDepositId = a.BankDepositId, Cash = a.Cash, InHandCash = a.InHandCash, Date = a.Date, CreatedDate = a.CreatedDate, CreatedBy = a.CreatedBy,
                            UserName = c.StaffName
                        }).ToList();
            }
            else {

                data = (from a in _context.BankDeposits
                        join b in _context.Users on a.CreatedBy equals b.UserId
                        join c in _context.Staffs on b.StaffId equals c.StaffId
                        where a.Status == 1
                        select new BankDepositViewModel {
                            BankDepositId = a.BankDepositId, Cash = a.Cash, InHandCash = a.InHandCash, Date = a.Date, CreatedDate = a.CreatedDate, CreatedBy = a.CreatedBy,
                            UserName = c.StaffName
                        }).ToList();
            }

            return View(data);
        }

        public IActionResult BankDepositDetailView(string breadCumValue, long bankDepositId) {
            if (HttpContext.Session.GetString("loggedIn") == null || HttpContext.Session.GetString("loggedIn") == "false") {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.breadCumValue = breadCumValue;
            ViewBag.IsUpdate = bankDepositId > 0 ? "true" : "false";

            BankDepositViewModel bankDepositViewModel = new BankDepositViewModel();

            if (bankDepositId > 0) {
                bankDepositViewModel = (from a in _context.BankDeposits where a.BankDepositId == bankDepositId

                                        select new BankDepositViewModel() {
                                            BankDepositId = a.BankDepositId, Cash = a.Cash, InHandCash = a.InHandCash, Date = a.Date, CreatedBy = a.CreatedBy,
                                            ThirdPartyChequesId = a.BankDepositThirdPartyCheques.Select(x => x.ThirdPartyChequeId).ToList()
                                        }).Single();
                bankDepositViewModel.ChequeTotal = _context.ThirdPartyCheques
                    .Where(x => bankDepositViewModel.ThirdPartyChequesId.Contains(x.ThirdPartyChequeId)).Sum(s => s.Amount);
            }

            bankDepositViewModel.ThirdPartyChequesList = _context.ThirdPartyCheques.Select(x => new ThirdPartyCheque() {
                ThirdPartyChequeId = x.ThirdPartyChequeId, ChequeCode = x.ChequeCode, Amount = x.Amount
            }).ToList();

            return View(bankDepositViewModel);
        }
    }
}

Sharmila-Textile-WebApp/Views/BankDeposit/BankDepositListView.cshtml
@model List<Sharmila_Textile_WebApp.ViewModel.BankDepositViewModel>

@{
    ViewData["Title"] = "Bank Deposit List View";
}

<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Bank Deposit</li>
                </ol>
            </nav>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="Search...">
                    <button type="button" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        @* <span class="notification">5</span> *@
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Mike John responded to your email</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="#">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Login" asp-action="Logout">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <hr />
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                <a class="btn btn-primary float-right" asp-controller="BankDeposit" asp-action="BankDepositDetailView" asp-route-breadcumValue="Create New Bank Deposit">
                    <i class="material-icons">add</i> Create New Bank Deposit
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card mt-0">
                    <div class="card-body">
                        <table id="dataTbl" class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th> 
                                    <th>Cash</th>  
                                    <th>In-Hand Cash</th>  
                                    <th>  Date</th> 
                                    <th>Created Date</th> 
                                    <th>Created By</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model) {
                                    <tr>
                                        <td class="text-center">@item.BankDepositId</td> 
                                        <td>@item.Cash.ToString("N2")</td>  
                                        <td>@item.InHandCash.ToString("N2")</td>  
                                        <td>@item.Date.ToString("yyyy-MM-dd")</td> 
                                        <td>@item.CreatedDate.ToString("yyyy-MM-dd")</td> 
                                        <td>@item.UserName</td>
                                        <td class="td-actions text-center">
                                            <a type="button" rel="tooltip" class="btn btn-success" asp-controller="BankDeposit" asp-action="BankDepositDetailView" asp-route-breadcumValue="Edit Bank Deposit" asp-route-bankDepositId="@item.BankDepositId">
                                                <i class="material-icons">visibility</i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        var myTable = $('#dataTbl').DataTable();
        $('#dataTbl_filter').addClass("float-right");
    });
</script>