Sharmila-Textile-WebApp/Models/SupplierAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Sharmila_Textile_WebApp.Models {
    [Table("SUPPLIER_ACCOUNT")] 
    public class SupplierAccount {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("SUPPLIER_ACCOUNTS_ID")]
        public long SupplierAccountId { get; set; }

        [Column("DESCRIPTION", TypeName = "varchar(100)")]
        public string Description { get; set; }

        [Column("AMOUNT", TypeName = "decimal(18, 2)")]
        public decimal Amount { get; set; }

        [Column("CREATED_DATE")]
        public DateTime CreatedDate { get; set; }

        [Column("DATE")]
        public DateTime Date { get; set; }

        [Column("ACCOUNT_TYPE")]
        public string AccountType { get; set; }

        [Column("SUPPLIER_ID")]
        public long SupplierId { get; set; }

        [Column("CREATED_BY")]
        public long CreatedBy { get; set; }

        [Column("REMARK", TypeName = "varchar(100)")]
        public string Remark { get; set; }

        [Column("STATUS")]
        public int Status { get; set; }

        public Supplier Supplier { get; set; }

        [ForeignKey("CreatedBy")]
        public User User { get; set; }

        public List<SupplierAccountOwnCheque> SupplierAccountOwnCheques { get; set; }
        public List<SupplierAccountThirdPartyCheque> SupplierAccountThirdPartyCheques { get; set; }
    }
}

Sharmila-Textile-WebApp/Controllers/SupplierAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sharmila_Textile_WebApp.Data;
using Sharmila_Textile_WebApp.Models;
using Sharmila_Textile_WebApp.ViewModel;

namespace Sharmila_Textile_WebApp.Controllers {
    public class SupplierAccountController : Controller {
        private readonly AppDBContext _context;
        private readonly IMapper _mapper;

        public SupplierAccountController(AppDBContext context, IMapper mapper) {
            _context = context;
            _mapper = mapper;
        }

        public IActionResult SupplierAccountListView(string date) {
            if (HttpContext.Session.GetString("loggedIn") == null || HttpContext.Session.GetString("loggedIn") == "false") {
                return RedirectToAction("Index", "Login");
            }
            List<SupplierAccountViewModel> data;
            if (date != null) { 
                data = (from a in _context.SupplierAccounts
                    join b in _context.Suppliers on a.SupplierId equals b.SupplierId
                    join c in _context.Users on a.CreatedBy equals c.UserId
                    join d in _context.Staffs on c.StaffId equals d.StaffId
                    where a.Status == 1 && a.Date == Convert.ToDateTime(date)
                        select new SupplierAccountViewModel {
                        SupplierAccountId = a.SupplierAccountId, Description = a.Description, Amount = a.Amount, AccountType = a.AccountType,
                        CreatedDate = a.CreatedDate, SupplierName = b.SupplierName, Date = a.Date, UserName = d.StaffName
                    }).ToList();
            }
            else {
                  data = (from a in _context.SupplierAccounts
                        join b in _context.Suppliers on a.SupplierId equals b.SupplierId
                        join c in _context.Users on a.CreatedBy equals c.UserId
                        join d in _context.Staffs on c.StaffId equals d.StaffId
                        where a.Status == 1
                        select new SupplierAccountViewModel {
                            SupplierAccountId = a.SupplierAccountId, Description = a.Description, Amount = a.Amount, AccountType = a.AccountType,
                            CreatedDate = a.CreatedDate, SupplierName = b.SupplierName, Date = a.Date, UserName = d.StaffName
                        }).ToList();
            }

            return View(data);
        }

        public IActionResult SupplierAccountDetailView(string breadCumValue, long supAccId) {
            if (HttpContext.Session.GetString("loggedIn") == null || HttpContext.Session.GetString("loggedIn") == "false") {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.breadCumValue = breadCumValue;
            ViewBag.IsUpdate = supAccId > 0 ? "true" : "false";

            SupplierAccountViewModel supplierAccountViewModel = new SupplierAccountViewModel();

            if (supAccId > 0) {
                supplierAccountViewModel = (from a in _context.SupplierAccounts where a.SupplierAccountId == supAccId
                                            select new SupplierAccountViewModel {
                                                SupplierAccountId = a.SupplierAccountId, Description = a.Description, Amount = a.Amount, AccountType = a.AccountType,
                                                CreatedDate = a.CreatedDate, Remark = a.Remark, SupplierId = a.SupplierId, CreatedBy = a.CreatedBy, Date = a.Date,
                                                OwnChequesId = a.SupplierAccountOwnCheques.Select(x => x.OwnChequeId).ToList(),
                                                ThirdPartyChequesId = a.SupplierAccountThirdPartyCheques.Select(x => x.ThirdPartyChequeId).ToList()
                                            }).Single();
            }

            supplierAccountViewModel.SupplierList = _context.Customers.Where(s => s.CurrentStatus == 1).Select(x => new Supplier() {
                SupplierId = x.CustomerId, SupplierName = x.CustomerName
            }).ToList();
            supplierAccountViewModel.OwnChequesList = _context.OwnCheques.Select(x => new OwnCheque() {
                OwnChequeId = x.OwnChequeId, ChequeCode = x.ChequeCode, Amount = x.Amount
            }).ToList();
            supplierAccountViewModel.ThirdPartyChequesList = _context.ThirdPartyCheques.Select(x => new ThirdPartyCheque() {
                ThirdPartyChequeId = x.ThirdPartyChequeId, ChequeCode = x.ChequeCode, Amount = x.Amount
            }).ToList();

            return View(supplierAccountViewModel);

        }

    }
}

Sharmila-Textile-WebApp/Views/SupplierAccount/SupplierAccountListView.cshtml
@model List<Sharmila_Textile_WebApp.ViewModel.SupplierAccountViewModel>

@{
    ViewData["Title"] = "Supplier Account List View";
}

<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Supplier Accounts</li>
                </ol>
            </nav>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="Search...">
                    <button type="button" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        @* <span class="notification">5</span> *@
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Mike John responded to your email</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="#">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Login" asp-action="Logout">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <hr />
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                <a class="btn btn-primary float-right" asp-controller="SupplierAccount" asp-action="SupplierAccountDetailView" asp-route-breadcumValue="Create New Supplier Account">
                    <i class="material-icons">add</i> Create New Supplier Account
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card mt-0">
                    <div class="card-body">
                        <table id="dataTbl" class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Description</th>
                                    <th>Amount</th>
                                    <th>Account Type</th>
                                    <th>Date</th>
                                    <th>Created Date</th>
                                    <th>Supplier</th>
                                    <th>Created By</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model) {
                                    <tr>
                                        <td class="text-center">@item.SupplierAccountId</td>
                                        <td>@item.Description</td>
                                        <td>@item.Amount.ToString("N2")</td>
                                        <td>@item.AccountType</td>
                                        <td>@item.Date.ToString("yyyy-MM-dd")</td>
                                        <td>@item.CreatedDate.ToString("yyyy-MM-dd")</td>
                                        <td>@item.SupplierName</td>
                                        <td>@item.UserName</td>
                                        <td class="td-actions text-center">
                                            <a type="button" rel="tooltip" class="btn btn-success" asp-controller="SupplierAccount" asp-action="SupplierAccountDetailView" asp-route-breadcumValue="Edit Supplier Account" asp-route-supAccId="@item.SupplierAccountId">
                                                <i class="material-icons">visibility</i>
                                            </a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        var myTable = $('#dataTbl').DataTable();
        $('#dataTbl_filter').addClass("float-right");
    });
</script>