Sharmila-Textile-WebApp/Models/ThirdPartyCheque.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Sharmila_Textile_WebApp.Models {
    [Table("THIRD_PARTY_CHEQUE")]
    public class ThirdPartyCheque {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("THIRD_PARTY_CHEQUE_ID")]
        public long ThirdPartyChequeId { get; set; }

        [Column("CHEQUE_CODE", TypeName = "varchar(50)")]
        public string ChequeCode { get; set; }

        [Column("BANK", TypeName = "varchar(70)")]
        public string Bank { get; set; }

        [Column("BRANCH", TypeName = "varchar(70)")]
        public string Branch { get; set; }

        [Column("AMOUNT", TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        [Column("DATE", TypeName = "datetime")]
        public DateTime Date { get; set; }

        [Column("DUE_DATE", TypeName = "datetime")]
        public DateTime DueDate { get; set; }

        [Column("REMARK", TypeName = "varchar(100)")]
        public string Remark { get; set; }

        [Column("STATUS")]
        public long Status { get; set; }

        [Column("FROM", TypeName = "varchar(70)")]
        public string From { get; set; }

        [Column("FROM_REFERENCE_ID")]
        public long? FromReferenceId { get; set; }

        [Column("FROM_REFERENCE_NOTE")]
        public long? FromReferenceNote { get; set; }

        [ForeignKey("Status")]
        public ChequeStatus ChequeStatus { get; set; }
        public List<SupplierPaymentThirdPartyCheque> SupplierPaymentThirdPartyCheques { get; set; }
        public List<CollectionThirdPartyCheque> CollectionThirdPartyCheques { get; set; }
        public List<CustomerAccountThirdPartyCheque> CustomerAccountThirdPartyCheques { get; set; }
        public List<SupplierAccountThirdPartyCheque> SupplierAccountThirdPartyCheques { get; set; }
        public List<ExpenseThirdPartyCheque> ExpenseThirdPartyCheques { get; set; }
        public List<BankDepositThirdPartyCheque> BankDepositThirdPartyCheques { get; set; }
    }
}

Sharmila-Textile-WebApp/Controllers/ThirdPartyChequeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sharmila_Textile_WebApp.Data;
using Sharmila_Textile_WebApp.Models;
using Sharmila_Textile_WebApp.ViewModel;

namespace Sharmila_Textile_WebApp.Controllers {
    public class ThirdPartyChequeController : Controller {
        private readonly AppDBContext _context;
        private readonly IMapper _mapper;

        public ThirdPartyChequeController(AppDBContext context, IMapper mapper) {
            _context = context;
            _mapper = mapper;
        }

        public IActionResult ThirdPartyChequeList() {
            if (HttpContext.Session.GetString("loggedIn") == null || HttpContext.Session.GetString("loggedIn") == "false") {
                return RedirectToAction("Index", "Login");
            }
            var data = (from a in _context.ThirdPartyCheques
                        join b in _context.ChequeStatuses on a.Status equals b.ChequeStatusId
                        select new ThirdPartyChequeViewModel {
                            ThirdPartyChequeId = a.ThirdPartyChequeId, ChequeCode = a.ChequeCode, Bank = a.Bank, Branch = a.Branch, Amount = a.Amount,
                            DueDate = a.DueDate, StatusId = b.ChequeStatusId, Status = b.StatusName, Remark = a.Remark, Date = a.Date
                        }).ToList();

            return View(data);
        }

        public IActionResult ThirdPartyChequeDetailView(string breadCumValue, long thirdPartyChequeId) {
            if (HttpContext.Session.GetString("loggedIn") == null || HttpContext.Session.GetString("loggedIn") == "false") {
                return RedirectToAction("Index", "Login");
            }
            ViewBag.breadCumValue = breadCumValue;
            ViewBag.IsUpdate = thirdPartyChequeId > 0 ? "true" : "false";

            ThirdPartyChequeViewModel thirdPartyChequeViewModel = new ThirdPartyChequeViewModel();

            if (thirdPartyChequeId > 0) {
                thirdPartyChequeViewModel = _mapper
                    .Map<ThirdPartyChequeViewModel>(_context.ThirdPartyCheques.SingleOrDefault(x => x.ThirdPartyChequeId == thirdPartyChequeId));

            }


            thirdPartyChequeViewModel.ChequeStatusesVm = _mapper.Map<List<ChequeStatusViewModel>>(_context.ChequeStatuses.Where(x => x.StatusType.Contains("CH")).ToList());
            thirdPartyChequeViewModel.BankList = _context.ThirdPartyCheques.Select(x => x.Bank).Distinct().ToList();
            thirdPartyChequeViewModel.BranchList = _context.ThirdPartyCheques.Select(x => x.Branch).Distinct().ToList();

            thirdPartyChequeViewModel.CustomerList = _context.Customers.Where(s => s.CurrentStatus == 1).Select(x => new Customer() {
                CustomerId = x.CustomerId, CustomerName = x.CustomerName
            }).ToList();
            thirdPartyChequeViewModel.SupplierList = _context.Suppliers.Where(s => s.CurrentStatus == 1).Select(x => new Supplier() {
                SupplierId = x.SupplierId, SupplierName = x.SupplierName
            }).ToList();

            return View(thirdPartyChequeViewModel);
        }
    }
}

Sharmila-Textile-WebApp/Views/ThirdPartyCheque/ThirdPartyChequeList.cshtml
@model List<Sharmila_Textile_WebApp.ViewModel.ThirdPartyChequeViewModel>
@{
    ViewData["Title"] = "Third Party Cheque List";
}

<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <nav aria-label="breadcrumb" role="navigation">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">Third Party Cheque</li>
                </ol>
            </nav>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="Search...">
                    <button type="button" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        @* <span class="notification">5</span> *@
                        <p class="d-lg-none d-md-block">
                            Some Actions
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Mike John responded to your email</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">person</i>
                        <p class="d-lg-none d-md-block">
                            Account
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                        <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="#">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Login" asp-action="Logout">Log out</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <hr />
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                <a class="btn btn-primary float-right" asp-controller="ThirdPartyCheque" asp-action="ThirdPartyChequeDetailView" asp-route-breadcumValue="Create ThirdParty Cheque">
                    <i class="material-icons">add</i> Create ThirdParty Cheque
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="card mt-0">
                    <div class="card-body">
                        <table id="dataTbl" class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Cheque Code</th>
                                    <th>Bank</th>
                                    <th>Branch</th>
                                    <th>Amount</th>
                                    <th>Date</th>
                                    <th>Due Date</th>
                                    <th>Status</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model) {
                                    <tr>
                                        <td class="text-center">@item.ThirdPartyChequeId</td>
                                        <td>@item.ChequeCode</td>
                                        <td>@item.Bank</td>
                                        <td>@item.Branch</td>
                                        <td>@item.Amount.ToString("N2")</td>
                                        <td>@item.Date.ToString("yyyy-MM-dd")</td>
                                        <td>@item.DueDate.ToString("yyyy-MM-dd")</td>
                                        <td>@item.Status</td>
                                        <td class="td-actions text-center">
                                            <a type="button" rel="tooltip" class="btn btn-success" asp-controller="ThirdPartyCheque" asp-action="ThirdPartyChequeDetailView" asp-route-breadcumValue="Edit Third Party Cheque" asp-route-thirdPartyChequeId="@item.ThirdPartyChequeId">
                                                <i class="material-icons">visibility</i>
                                            </a>
                                        </td>
                                    </tr>
                                } 
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        var myTable = $('#dataTbl').DataTable();
        $('#dataTbl_filter').addClass("float-right");
    });
</script>